Use sh instead of tcsh for scripts.
While there, add support for redirecting output to a file.
Sponsored by:	Netflix

diff --git a/state-event-engine/rcv-syn-established/run-all-rcv-syn-established-tests b/state-event-engine/rcv-syn-established/run-all-rcv-syn-established-tests
--- a/state-event-engine/rcv-syn-established/run-all-rcv-syn-established-tests
+++ b/state-event-engine/rcv-syn-established/run-all-rcv-syn-established-tests
@@ -1,4 +1,4 @@
-#!/usr/bin/env tcsh
+#!/usr/bin/env sh
 #
 # Copyright (c) 2016 Michael Tuexen
 # All rights reserved.
@@ -25,73 +25,119 @@
 # SUCH DAMAGE.
 #
 
-set packetdrill = /usr/local/bin/packetdrill
-set delay = 1
-set limit = 10
-set testcases = ( rcv-syn-established-outside-left-secure-ipv4 \
-                  rcv-syn-established-outside-left-secure-ipv6 \
-                  rcv-syn-established-left-edge-secure-ipv4 \
-                  rcv-syn-established-left-edge-secure-ipv6 \
-                  rcv-syn-established-right-edge-secure-ipv4 \
-                  rcv-syn-established-right-edge-secure-ipv6 \
-                  rcv-syn-established-outside-right-secure-ipv4 \
-                  rcv-syn-established-outside-right-secure-ipv6 \
-                  rcv-syn-established-outside-left-insecure-ipv4 \
-                  rcv-syn-established-outside-left-insecure-ipv6 \
-                  rcv-syn-established-left-edge-insecure-ipv4 \
-                  rcv-syn-established-left-edge-insecure-ipv6 \
-                  rcv-syn-established-right-edge-insecure-ipv4 \
-                  rcv-syn-established-right-edge-insecure-ipv6 \
-                  rcv-syn-established-outside-right-insecure-ipv4 \
-                  rcv-syn-established-outside-right-insecure-ipv6 )
+packetdrill=/usr/local/bin/packetdrill
+delay=1
+timelimit=10
+testcases="rcv-syn-established-outside-left-secure-ipv4 \
+           rcv-syn-established-outside-left-secure-ipv6 \
+           rcv-syn-established-left-edge-secure-ipv4 \
+           rcv-syn-established-left-edge-secure-ipv6 \
+           rcv-syn-established-right-edge-secure-ipv4 \
+           rcv-syn-established-right-edge-secure-ipv6 \
+           rcv-syn-established-outside-right-secure-ipv4 \
+           rcv-syn-established-outside-right-secure-ipv6 \
+           rcv-syn-established-outside-left-insecure-ipv4 \
+           rcv-syn-established-outside-left-insecure-ipv6 \
+           rcv-syn-established-left-edge-insecure-ipv4 \
+           rcv-syn-established-left-edge-insecure-ipv6 \
+           rcv-syn-established-right-edge-insecure-ipv4 \
+           rcv-syn-established-right-edge-insecure-ipv6 \
+           rcv-syn-established-outside-right-insecure-ipv4 \
+           rcv-syn-established-outside-right-insecure-ipv6"
 
-set rootdir = `/usr/bin/dirname $0`
-set passed = 0
-set failed = 0
-set run = 0
-set skipped = 0
-set timedout = 0
-set first = 1
+rootdir=`/usr/bin/dirname $0`
+passed=0
+failed=0
+run=0
+skipped=0
+timedout=0
+first=1
 
 printf "Name                                                                    Verdict\n"
 printf "===============================================================================\n"
-foreach testcase ($testcases)
+for testcase in $testcases
+do
   printf "%-68.68s " `/usr/bin/basename $testcase`
-  if ($first == 0) then
-    if ($delay != 0) then
-      printf "\033[33m%10s\033[0m" "WAITING"
+  if [ $first -eq 0 ]
+  then
+    if [ $delay -ne 0 ]
+    then
+      if [ -t 1 ]
+      then
+        printf "\033[33m%10s\033[0m" "WAITING"
+      fi
       sleep $delay
-      printf "\b\b\b\b\b\b\b\b\b\b"
-    endif
+      if [ -t 1 ]
+      then
+        printf "\b\b\b\b\b\b\b\b\b\b"
+      fi
+    fi
   else
-    set first = 0
-  endif
-  printf "\033[33m%10s\033[0m" "RUNNING"
-  if (-f ${rootdir}/${testcase}.pkt) then
-    timeout $limit $packetdrill ${rootdir}/${testcase}.pkt >& /dev/null
-    set result = $status
-    set found = 1
+    first=0
+  fi
+  if [ -t 1 ]
+  then
+    printf "\033[33m%10s\033[0m" "RUNNING"
+  fi
+  if [ -f ${rootdir}/${testcase}.pkt ]
+  then
+    timeout $timelimit $packetdrill ${rootdir}/${testcase}.pkt >/dev/null 2>&1
+    result=$?
+    found=1
   else
-    set found = 0
-  endif
-  printf "\b\b\b\b\b\b\b\b\b\b"
-  if ($found == 1) then
-    if ($result == 0) then
-      @ passed++
-      printf "\033[32m%10s\033[0m\n" "PASSED"
-    else if ($result == 1) then
-      @ failed++
-      printf "\033[31m%10s\033[0m\n" "FAILED"
+    found=0
+  fi
+  if [ -t 1 ]
+  then
+    printf "\b\b\b\b\b\b\b\b\b\b"
+  fi
+  if [ $found -eq 1 ]
+  then
+    case $result in
+      0) passed=`expr $passed + 1`
+         if [ -t 1 ]
+         then
+           printf "\033[32m%10s\033[0m\n" "PASSED"
+         else
+           printf "%10s\n" "PASSED"
+         fi
+         ;;
+      1) failed=`expr $failed + 1`
+         if [ -t 1 ]
+         then
+           printf "\033[31m%10s\033[0m\n" "FAILED"
+         else
+           printf "%10s\n" "FAILED"
+         fi
+         ;;
+    124) timedout=`expr $timedout + 1`
+         if [ -t 1 ]
+         then
+           printf "\033[35m%10s\033[0m\n" "TIMEDOUT"
+         else
+           printf "%10s\n" "TIMEDOUT"
+         fi
+         ;;
+      *)
+         if [ -t 1 ]
+         then
+           printf "\033[36m%10s\033[0m\n" "UNKNOWN"
+         else
+           printf "%10s\n" "UNKNOWN"
+         fi
+         ;;
+    esac
+    run=`expr $run + 1`
+  else
+    if [ -t 1 ]
+    then
+      printf "\033[34m%10s\033[0m\n" "SKIPPED"
     else
-      @ timedout++
-      printf "\033[35m%10s\033[0m\n" "TIMEDOUT"
-    endif
-    @ run++
-  else
-    printf "\033[34m%10s\033[0m\n" "SKIPPED"
-    @ skipped++
-  endif
-end
+      printf "%10s\n" "SKIPPED"
+    fi
+    skipped=`expr $skipped + 1`
+  fi
+done
 printf "===============================================================================\n"
 printf "Summary: Number of tests run:       %3u\n" $run
 printf "         Number of tests passed:    %3u\n" $passed
